version: '3'
services:
celery:
    hostname: celery
    image: celery:latest
    ports:
     - "5001:5001"
     
services:
flower:
    hostname: flower
    image: flower:latest
    ports:
     - "5002:5002"
     
services:
rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=mypass
    ports:
        - "5003:5003"

